import "../../img/svg/play.svg"
import "../../img/svg/mute.svg"
import "../../img/svg/construction.svg"
import "../../img/svg/project.svg"
import "../../img/svg/design.svg"
import "../../img/svg/repairs.svg"
import "../../img/svg/right-arrow.svg"
import "../../img/svg/left-arrow.svg"